### ISSUE TITLE
Optimize SVG output

### ISSUE THREAD

**Issue by ngocdaothanh** [nbedos/termtosvg#103]
|  Input | Input size | Output size |
|---|---|---|
| https://asciinema.org/a/170142 | 1.6 MB | 44 MB |
| https://asciinema.org/a/234628| 4.2 MB | 22 MB |

The output files are useless because:
* Chrome can't load the SVG files.
* Running [svgo](https://github.com/svg/svgo) on the output files will cause out of memory error.

Can termtosvg output smaller files?

**Comment by nbedos** [comment]
There is not much I can do. If you want `termtosvg` to output a small file you should
* Record a small screen
* Use colors sparingly. `lolcat` as used in 234628 is the worst since it causes every character to have it's own color so in the resulting SVG you have one `<text>` tag per character. So of course it's the output is huge.
* If there is lot of data scrolling off of the screen, use the `-m` command line option to put a cap on the framerate. This reduces the number of frames in the SVG and the size of the file.

For the two cast files you provided I can get the size of the SVG file under 5Mb by using 
`termtosvg render -m 50 234628.cast` (3.1 Mb) and `termtosvg render -m 200 170142.cast` (5Mb)

Of course the price is that the output is less smooth though for 234628 I don't think it's that noticeable.

Let me know if that helps.

**Comment by ngocdaothanh** [comment]
> use the -m command line option to put a cap on the framerate

👍 Great tip!

I'll close this issue.
