### ISSUE TITLE
Suggestion: Width 100%

### ISSUE THREAD

**Issue by DannyBen** [nbedos/termtosvg#104]
Not sure if this was discussed before and decided against - but if it wasn't:

Why not set `width="100%"` in the output SVG instead of the width of the `viewBox`?

This will make it a nice SVG that takes the width of whatever container it sits in.

**Comment by nbedos** [comment]
Off the top of my head I think I use the width of the viewBox because termtosvg relies on a few hardcoded values for the width and height of a character cell. It works well at a scale of 1 but may break in other cases (e.g. by showing a gap between two adjacent characters with differing background colors).

It's more of a precaution, `width="100%"` should work fine in most cases.

**Comment by DannyBen** [comment]
I see. Thanks.
