### ISSUE TITLE
Remove "exit" from svg animation

### ISSUE THREAD

**Issue by DhruvDh** [nbedos/termtosvg#106]
I am using termtosvg through Ubuntu on WSL. My animations all seem to have the "exiting" included in them, which feels kind of off-putting.

Example here - https://dhruvdh.github.io/ni/11_reactivity.html

I think it would be nice for there to be an option that makes it possible to exclude the "exit" from the final animation.

I ended the recording using `Ctrl+D`, in case this information is useful.

**Comment by DhruvDh** [comment]
I realize I haven't been very clear in wording this issue. What I mean is at the end of each animation, there is an appearance of the word "exit" is `Ctrl+D` is pressed, or the user typing `exit` if that is how the user chose to stop the recording.

And I think it's best for this behavior to be optional.

**Comment by nbedos** [comment]
When you start a recording, `termtosvg` spawns a new `$SHELL` process (or whatever command is specified by the `-c` command line argument). The recording stops when the process exits, so in the case of `$SHELL` it stops when you type `exit` or press `Ctrl+D` because that causes the shell session to terminate. What I'm trying to say is that "exit" is printed by the process being recorded, it's not a command of termtosvg. Excluding this from the output was already discussed in https://github.com/nbedos/termtosvg/issues/11 and I don't think it is possible to do it in a reliable way.

However, you can remove "exit" by manually the recording :

1. Record you animation : `termtosvg record`. This will create a file with the extension `.cast`
2. Open the `.cast` file with a text editor and remove the last few lines of the recording that show "exit" on screen. In the example below you would delete all the lines starting from time=3.458432
3. Render the animation : `termtosvg render your_file.cast`

```
{"version": 2, "width": 191, "height": 53}
[0.0, "o", "\u001b[0;31mnico \u001b[0;34m~\u001b[0;31m $ \u001b[0m"]
[0.375827, "o", "d"]
[0.407796, "o", "a"]
[0.656532, "o", "t"]
[0.735655, "o", "e"]
[1.27972, "o", "\r\n"]
[1.282084, "o", "Sat 26 Oct 2019 11:41:48 AM CEST\r\n"]
[1.282541, "o", "\u001b[0;31mnico \u001b[0;34m~\u001b[0;31m $ \u001b[0m"]
[1.743811, "o", "d"]
[1.823795, "o", "a"]
[2.351762, "o", "t"]
[2.407759, "o", "e"]
[3.455783, "o", "\r\n"]
[3.457858, "o", "Sat 26 Oct 2019 11:41:51 AM CEST\r\n"]
[3.458432, "o", "\u001b[0;31mnico \u001b[0;34m~\u001b[0;31m $ \u001b[0m"]
[3.775725, "o", "e"]
[3.823718, "o", "x"]
[4.215733, "o", "i"]
[4.303709, "o", "t"]
[4.631675, "o", "\r\n"]
[4.631931, "o", "exit\r\n"]
```

**Comment by DhruvDh** [comment]
Thank you for taking the time for an detailed explanation instead of simply telling me what to do! It is very much appreciated.

Later when I have time I'll try to see if it's possible for me to implement an option for the record command that get's rid of exit from the `.cast` file automatically and send a PR.

**Comment by ialbert** [comment]
I agree with @DhruvDh the last exit is distracting and "ruins" the utility of the tool. It inserts the `exit` command basically it makes the tool operation leak into the recording itself.

Especially in the context of using the tool to demonstrate command-line tools, it shows a command that we DO NOT want people to enter! The `exit` is there to stop the recording!

**Comment by nbedos** [comment]
> The `exit` is there to stop the recording - it has no place in the recording.
The recording stops when the process being recorded exits. If you're recording a shell session, yes, it will stop when entering "exit" or Control-D, but it's the shell that prints "exit" on screen. termtosvg shouldn't discard any information printed on screen by the process it records. And if termtosvg did discard information, it should do so reliably.

As already mentioned above I don't think there is a reliable way for termtosvg to detect which part of the recording should be discarded. The PR you just opened may work for your very own use case but it will fail when exiting a shell with another means than Control+D, or when recording a program that is not a shell, or when recording a shell that does not print "exit" on screen.

**Comment by ialbert** [comment]
When we record a terminal the tool should not force us to record the keypresses that are not part of what we try to demonstrate.

Moreover, even though we press Ctrl-D it gets translated to the word "exit" which is actually confusing on top of everything, we did not type "exit" ourselves, yet the capture shows that.

My fix actually works surprisingly well. If one types `exit` then it keeps that fully since the last command is an enter that gets dropped. If one presses Ctrl-D then it cuts out the word being translated and does not mislead the viewer.

**Comment by ialbert** [comment]
Also: I am quite convinced that the use-case that I demonstrate is what close to overwhelming majority (100%?) of the users of this library need. It really makes no sense to end every screen cap with an exit and mislead users into thinking they have to type exit to finish the demo.

**Comment by nbedos** [comment]
> When we record a terminal the tool should not force us to record the keypresses that are not part of what we try to demonstrate.

termtosvg records what's printed on the screen. It's not meant to second guess what you want recorded or not. If you want to preprocess your recording, run a three-step recording process:

1. `termtosvg record recording.cast` to record
2. Edit `recording.cast` based on your personal needs, either manually or automatically
3. `termtosvg render recording.cast` to render the animation

This is way more powerful than anything that I can offer. But yes, it puts the burden on users.

> My fix actually works surprisingly well. If one types `exit` then it keeps that fully since the last command is an enter that gets dropped. If one presses Ctrl-D then it cuts out the word being translated and does not mislead the viewer.

It works for your own use case but currently breaks concurrency and all recordings for which you don't want the last frame dropped (e.g. most recording of something else than a shell session such as `termtosvg -c python`)

> It really makes no sense to end every screen cap with the word `exit` and mislead users into thinking they have to type exit to finish the commands themselves.

Well, your shell prints "exit" on exit. If you don't like it, use a shell that doesn't.

> You are too hung up in the specifics of "but shouldn't the library fulfill its promise of capturing everything" instead of what is this thing used for?

Yes, I do believe that a "terminal recorder" should record as faithfully as possible and I won't bake a pre-processing step into termtosvg to clean up the output of some programs.
