### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by sammcj** [nbedos/termtosvg#22]
It would be great if this was added to homebrew for easy package management / upgrades / portability etc...

https://docs.brew.sh/Formula-Cookbook

* Edit, also this is one of the most useful applications I've found recently, so thank you for creating something that's a) not written in javascript b) outputs to svg and c) doesn't upload your recordings to some cloud service. 🍺

**Comment by phaus** [comment]
On its way… https://github.com/Homebrew/homebrew-core/pull/34577 :-)

**Comment by phaus** [comment]
Cool. Then I could do a proper test of the formula with the next update.
The Pull Request is still in review :-/.

**Comment by phaus** [comment]
@nbedos could you support me here? 

https://github.com/Homebrew/homebrew-core/pull/34577#issuecomment-446186669

I don't know much about the build system.

**Comment by nbedos** [comment]
@phaus I've answered the questions about resources and `.[dev]`. I don't know about `pipe_output` though. An alternative could be to upgrade the formula from termtosvg 0.6.0 to [0.7.0](https://github.com/nbedos/termtosvg/releases/tag/0.7.0) and run all unittest with `python -m unittest termtosvg.tests.suite` since it does not required using a pipe.

**Comment by phaus** [comment]
The formula was merged \o/.

**Comment by nbedos** [comment]
@phaus Great! Thanks! I'll leave this issue open so that in the future we can communicate about upgrades to the formula. Thanks again!
