### ISSUE TITLE
Colours not showing up properly.

### ISSUE THREAD

**Issue by shubham1172** [nbedos/termtosvg#43]
The color of the prompt is always like this no matter what theme I choose.
<img src="http://svgur.com/i/7Xo.svg"/>

**System specs**
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
FLAVOUR="Kubuntu"

**Comment by nbedos** [comment]
Could you record a .cast file with `termtosvg --record` and copy paste the content here?

**Comment by nbedos** [comment]
Thanks. Your prompt uses a bold font so termtosvg displays it with bright colors (color8 to color15 of the color themes defined in `~/.config/termtosvg/termtosvg.ini`). There are two solutions:
- Tweak a color theme so that color8 through color15 look like what you want
- If you don't care about bright colors, remove them altogether. For example you could add the following theme to the configuration file:
```
[solarized-dark-8]
foreground = #93a1a1
background = #002b36
color0 = #002b36
color1 = #dc322f
color2 = #859900
color3 = #b58900
color4 = #268bd2
color5 = #6c71c4
color6 = #2aa198
color7 = #93a1a1
```
and then call `termtosvg --theme solarized-dark-8`.

Let me know if it fixes your problem!

**Comment by shubham1172** [comment]
Great! It fixed my problem! Thanks!
