### ISSUE TITLE
Bright colored characters rendered as bold

### ISSUE THREAD

**Issue by nnist** [nbedos/termtosvg#58]
Currently, bold characters are correctly rendered. But bright colored characters are also rendered as bold, even when they should not be bold.

I think this happens because pyte makes bright colored characters bold; this should probably be overridden.

**Comment by nbedos** [comment]
Thanks for reporting this. I'm afraid that with the information I get from Pyte I can't make the distinction between bright characters that should be displayed bold and those which shouldn't.

Overriding colors defined by Pyte [1] to get "brightred" instead of "red" would probably make this work but it's ugly. I'll look into it.

[1] https://github.com/selectel/pyte/blob/master/pyte/graphics.py#L64

**Comment by nbedos** [comment]
I've looked into this but sadly I don't think it's possible. Basically with the information I have on a character rendered by Pyte I can't distinguish characters that should be displayed bold from character that should not. In both cases they have `bold=True` so I can tell if a bright character has `bold` set because the character is really bold or because it's displayed in a bright color.
