### ISSUE TITLE
How to use the resulting SVG on GitHub markdown

### ISSUE THREAD

**Issue by ahmetb** [nbedos/termtosvg#61]
It looks like the SVG in the README of termtosvg uses github.io to host the SVG.

When the `![](./img/foo.svg)` syntax used, the rendered GitHub HTML **does not actually animate** the SVG. :(

It seems like Github is restricting this ––but not when you do `<p><img src='//example.com/foo.svg'></p>`?

**Comment by nbedos** [comment]
Yeah, it's weird that it does not work when the image is inside the repository... The easiest way around this is to either use https://rawgit.com/ or setup a GitHub pages website for you repository and host the animation there.

**Comment by nnist** [comment]
I ran into the same problem, see [this stackoverflow post](https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown) for a more detailed explanation (and multiple ways to get around it). Apparently it's disabled due to potential cross site scripting vulnerabilities.

github.io is the preferred workaround.

**Comment by ahmetb** [comment]
Thanks for the answers. Closing this since it's not actionable. Feel free to add a note to README as you see fit.

**Comment by nbedos** [comment]
This issue is getting many more views than others so I'm temporarily reopening it to add that since https://github.com/nbedos/termtosvg/issues/86 was resolved, SVG animations produced by termtosvg can be included in a markdown file simply like so:

```markdown
![Example](./docs/examples/awesome_window_frame.svg)
```
You just have to have the mardown file and the SVG in the same repository. This is exactly how it's done in README.md : https://github.com/nbedos/termtosvg/blame/0.9.0/README.md#L8

Please [open an issue](https://github.com/nbedos/termtosvg/issues/new) if you still can not use the animations the way you'd like.
