### ISSUE TITLE
Maybe there is something wrong with the output of termtosvg

### ISSUE THREAD

**Issue by armsp** [nbedos/termtosvg#86]
I am not sure if this is the correct place to ask this, but my experiments led me to believe that there are some issues with the svg output by termtosvg.  
**Why?**  
The svgs output by _termtosvg_ don't seem to be rendered by GitHub, whereas other random online svgs and by another tool _svg-term-cli_ seem to work well with GitHub.  
**Test**  
I created [this repository](https://github.com/armsp/howto-render-svg) that showcases this well enough. svgs are inside `docs` folder and `README.md` tries to show them. All the svgs except your own svg that I downloded from your README as well as one that I made using your tool fail to render whereas others work.  
I tried all the ways I think -
- Relative path
- Github url
- Raw github url with sanitization `?sanitize=true`

Any idea why this might be happening ?

**Comment by armsp** [comment]
Corresponding [SO post](https://stackoverflow.com/questions/53702616/some-svg-animations-play-in-github-readme-others-do-not), just in case.

**Comment by nbedos** [comment]
> I am not sure if this is the correct place to ask this

It's the best place for this :) Thanks for reporting the issue.

I did some tests and it turns out GitHub sanitizes all relative links to SVG files in `README.md` by generating a full URL for this file that ends with `?sanitize=true`. The sanitized file is missing every `animate` element which is why the animation is broken.

A workaround for this is to link to the full URL of the SVG file hosted on GitHub pages (see [README.md](https://github.com/nbedos/termtosvg/blob/develop/README.md) for an example).

svg-term-cli uses CSS keyframes to animate the terminal screen by translating lines in and out of the viewable part of the image. GitHub seems to tolerate _that_ kind of animation so I'll consider switching to it.

I too thought it was just GitHub that required SVGs to be hosted elsewhere.

**Comment by nbedos** [comment]
@armsp 

> What would be the consequences of this switch?
> Would there be any trade-offs?

I don't know yet, I'll have to do some testing.

**Comment by nbedos** [comment]
It's been a while but I've finally found some time to work on this.

I changed termtosvg so that animations work roughly like those generated by svg-term-cli. These should bring the following improvements:

* Relative links to an SVG animation in markdown files on GitHub should now work
* Animations use way less CPU

I've only found one regression which is that using Firefox, when zooming on an animation, some lines jump up and down by one pixel between two frames. I cannot reproduce this issue with Chromium.

You can see here a README including a relative link to an animation : https://github.com/nbedos/termtosvg/blob/feature/css_animation/README.md

Updated examples are located here : https://github.com/nbedos/termtosvg/tree/feature/css_animation/docs/examples

I have to do a few more tests but it looks good so far.

**Comment by nbedos** [comment]
termtosvg now allows defining animations using either CSS or the Web Animations API.
CSS animations have a better compatibility with GitHub and should be used most of the time.
Animations defined via the Web Animations API are easier to control using JavaScript and should be prefered when interactivity is desired.

The choice to use CSS or WAAPI is done by template creators (see https://github.com/nbedos/termtosvg/blob/develop/man/termtosvg-templates.md)

This has been has been included in release [0.9.0](https://github.com/nbedos/termtosvg/releases/tag/0.9.0)
